theme: jekyll-theme-midnight

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      #permalink: /blog/:categories/:title/
      permalink: /pages-test/blog/:year/:month/:day/:title/
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default


giscus:
  repo:                "rajbos/pages-test"
  repo-id:             "449695114"
  category:            "Comments"
  category-id:         "[your-category-id]"
  mapping:             "url"
  reaction-enabled:    "1"
  theme:               "dark_dimmed"
  crossorigin:         "anonymous"